forestadmin_forest:
    resource: '@ForestAdminForestBundle/Controller'
    prefix:    /forest
forestadmin_forest_homepage:
    path:     /
    defaults: { _controller: ForestAdminForestBundle:Default:index }
