services:
    forestadmin.forest:
        class: ForestAdmin\ForestBundle\Service\ForestService
        arguments:
            - "@doctrine"
            - '%kernel.cache_dir%'
    forestadmin.liana:
        class: ForestAdmin\ForestBundle\Service\LianaService
        arguments:
            - collections
            - "@doctrine"
