services:
    forestadmin.forest:
        class: ForestAdmin\ForestBundle\Service\ForestService
        arguments:
            - "@container"
            - "@doctrine"
    forestadmin.liana:
        class: ForestAdmin\ForestBundle\Service\LianaService
        arguments:
            - collections
            - "@doctrine"
